version: '3.9'
services:
  php_tariffs:
    build:
      context: ./server
    container_name: php-tariffs-container
    networks:
      - server-net
    ports:
      - "30:9000"
    volumes:
      - ./server/app:/var/www/html/tariffs
    depends_on:
      - database_tariffs

  nginx_tariffs:
    image: nginx:stable-alpine
    container_name: nginx-tariffs-container
    networks:
      - server-net
    ports:
      - "31:80"
    volumes:
      - ./server/app:/var/www/html/tariffs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  database_tariffs:
    image: mariadb:11.2-jammy
    container_name: mariadb-tariffs-container
    networks:
      - server-net
    ports:
      - "32:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tariffs
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  server-net:
    driver: bridge
